services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres       
      POSTGRES_PASSWORD: 0764 
      POSTGRES_DB: to_do      
    ports:
      - "5432:5432"                  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
